### PR TITLE
Propogating IllegalArgumentException instead of silent failure in HiveDatasetFinder

### PR DESCRIPTION
**Pull request by aditya1105**

### CODE REVIEW

**Comment by ibuenros** [comment]
@aditya1105 will this cause immediate job failure? If so, we don't want that behavior.

**Comment by aditya1105** [comment]
@ibuenros gobblin job should fail whenever such a scenario occurs. Illegal argument exception should not be catched and logged.

**Comment by ibuenros** [comment]
I guess I don't exactly know when `IllegalArgumentException` is thrown. Any examples?

**Comment by aditya1105** [comment]
Mostly by com.google.common.base.Preconditions. In the current scenario, Preconditions are throwing IllegalArgumentException. Also IllegalArgumentException extends RuntimeException, so we should let it fail the job.

**Comment by abti** [comment]
Issue: https://issues.apache.org/jira/browse/GOBBLIN-13

Please update your PR title with following prefix: [GOBBLIN-13]

**Pull request merged**
