### PR TITLE
[GOBBLIN-10] Fix_for_#1850_and_#1851

### PR DESCRIPTION
**Pull request by kadaan**

### CODE REVIEW

**Comment by kadaan** [comment]
Fix for #1850 and #1851

**Comment by kadaan** [comment]
@abti Can you get someone to look at this?

**Comment by abti** [comment]
@kadaan will prioritize

**Comment by abti** [comment]
Issue: https://issues.apache.org/jira/browse/GOBBLIN-10

Please update your PR title with following prefix: [GOBBLIN-10]

**Comment by abti** [comment]
@kadaan Seems like findbugs is failing for this: https://travis-ci.org/apache/incubator-gobblin/builds/245976111?utm_source=github_status&utm_medium=notification

**Comment by abti** [comment]
It looks good to me, so let me know when you update the diff with findbugs resolved and I will merge it in.

**Comment by kadaan** [comment]
@abti Fixed the findbugs issue.

**Comment by abti** [comment]
Thanks

**Pull request closed without merging**
