### PR TITLE
Allow disabling global throttling. Fix a race condition in BatchedPer…

### PR DESCRIPTION
**Pull request by ibuenros**
…mitsRequester.

### CODE REVIEW

**Comment by ibuenros** [comment]
@yukuai518 can you review? Thanks!

**Comment by ibuenros** [comment]
@yukuai518 any comments?

**Comment by ibuenros** [comment]
@yukuai518 ping?

**Comment by abti** [comment]
Issue: https://issues.apache.org/jira/browse/GOBBLIN-24

Please update your PR title with following prefix: [GOBBLIN-24]

**Pull request merged**
