### PR TITLE
[Gobblin 98] Orc records get dropped and duplicated

### PR DESCRIPTION
**Pull request by PraTrick**
Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title.
    - https://issues.apache.org/jira/browse/GOBBLIN-98

### Description
- [ ] Here are some details about my PR:
  The Hive's OrcSerde caches converted records - the OrcSerde has a single org.apache.hadoop.hive.ql.io.orc.OrcSerde.OrcSerdeRow (basically an ArrayList) and every time the org.apache.hadoop.hive.serde2.Serializer#serialize(Object, ObjectInspector) method is called, the object is re-used.
  The problem is that org.apache.hadoop.hive.ql.io.orc.OrcSerde.OrcSerdeRow is package protected and has no public constructor, so no copy can be made. This would be fine if org.apache.hadoop.hive.ql.io.orc.OrcSerde.OrcSerdeRow is immediately written out. But all Gobblin jobs have a buffer that the writer reads from. This buffering can cause race conditions where records get dropped and duplicated.

### Tests
- [ ] My PR adds the following unit tests:
	- gobblin-core/src/test/java/gobblin/serde/HiveSerDeTest.java

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by aditya1105** [comment]
Hi @PraTrick ,
Can you try setting job property "fork.record.queue.capacity" to 1, and check if that works.
This is according to the doc, https://gobblin.readthedocs.io/en/latest/case-studies/Writing-ORC-Data/

**Comment by PraTrick** [comment]
The issue happens despite the setting the property
fork.record.queue.capacity *=* *1*.

**Comment by abti** [comment]
Please create a PR against master branch. 0.12.0 is a release branch.

**Comment by PraTrick** [comment]
Closing PR request as it was raised against the branch 0.12.0 which is a release branch. Will open it against the master branch.

**Pull request closed without merging**
