### PR TITLE
[GOBBLIN-205]Fix bug in pushmode copyRoute generation

### PR DESCRIPTION
**Pull request by autumnust**
Add some docs to help understand and maintain the code

**The major code fix is to change a `return` to `continue` in `generateDatasetInPushMode` to make sure that each end-point of Push Mode will traversed.** 

Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-205] My Gobblin PR"
    - https://issues.apache.org/jira/browse/GOBBLIN-205

### Description
- [x ] Here are some details about my PR, including screenshots (if applicable):

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by autumnust** [comment]
@ibuenros Can you help review on this? Thanks.

**Comment by ibuenros** [comment]
Can you explain what the issue was in the Jira ticket?

**Comment by autumnust** [comment]
The issue is, replication in Push-Mode doesn't generate workunits.  

Recall that in the push mode, the source is the `EndPoint` that runs the distcp job. The bug is in `ConfigBasedMultiDatasets.java`, in the iteration of line 130: If current `pushCandidate` is not the `EndPoint` that is running the push job, we should continue to iterate the list of `pushCandidate` instead of return immediately.

**Comment by ibuenros** [comment]
+1

**Pull request closed without merging**
