### PR TITLE
[GOBBLIN-9] Improve AdminUI and RestService with better sorting, filtering, auto-updates, etc.

### PR DESCRIPTION
**Pull request by kadaan**

### CODE REVIEW

**Comment by kadaan** [comment]
@shirshanka Can you guys give this a look.

**Comment by kadaan** [comment]
@abti Can you get someone to review this.

**Comment by abti** [comment]
@kadaan will review it

**Comment by abti** [comment]
Issue: https://issues.apache.org/jira/browse/GOBBLIN-9 

Please update your PR title with following prefix: [GOBBLIN-9]

**Comment by abti** [comment]
Changes merged.

**Pull request closed without merging**
