### PR TITLE
[GOBBLIN-1075] Add option to return latest failed flows

### PR DESCRIPTION
**Pull request by jack-moseley**
Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
    - https://issues.apache.org/jira/browse/GOBBLIN-1075

### Description
- [x] Here are some details about my PR, including screenshots (if applicable):

Add query boolean option that will only return failed flow statuses/executions.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

Updated test

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by jack-moseley** [comment]
@arjun4084346 please review

**Comment by arjun4084346** [comment]
I think instead of giving an option to return "failed" flows, we should give option to return flows with ANY status. e.g. how many flows are in COMPILED state, how many are RUNNING.... and so on

**Comment by arjun4084346** [comment]
We should also code it in an flexible way, so that now the filter supports a particular flow status(es) , and in future maybe a filter to support all GET flowConfigs with a particular config.
The second point can be really helpful, when users(SREs) have to add/change one config to multiple flows. This has happened in past. cc @Pawan Reddy

**Comment by jack-moseley** [comment]
> I think instead of giving an option to return "failed" flows, we should give option to return flows with ANY status. e.g. how many flows are in COMPILED state, how many are RUNNING.... and so on

This is a good idea, I modified it to instead take a query like `&executionStatus=RUNNING` which will return the last running flow.

**Comment by jack-moseley** [comment]
> We should also code it in an flexible way, so that now the filter supports a particular flow status(es) , and in future maybe a filter to support all GET flowConfigs with a particular config.
> The second point can be really helpful, when users(SREs) have to add/change one config to multiple flows. This has happened in past. cc @pawan Reddy

I'm not sure if that should be relevant to this PR, since the code paths for getting flowstatus/flowconfig are completely separate, and I don't think there's much else in flowstatus that would be useful to query by.

Maybe that is a change to getting flowconfig that we could do in the future though (being able to query which flowconfig have a particular key set, etc.)

**Comment by arjun4084346** [comment]
+1 LGTM.

**Comment by jack-moseley** [comment]
@sv2000 please merge

**Pull request closed without merging**
