### PR TITLE
[GOBBLIN-171] Add a writer wrapper that closes the wrapped writer and…

### PR DESCRIPTION
**Pull request by htran1**
… creates a new one

Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [x] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
    - https://issues.apache.org/jira/browse/GOBBLIN-171

### Description
- [x] Here are some details about my PR, including screenshots (if applicable):
Add a writer wrapper that closes the wrapped writer on flush. A new writer is created on the next write.

### Tests
- [x] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [x] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by htran1** [comment]
@abti, please review.

**Comment by abti** [comment]
Execution failed for task ':gobblin-restli:gobblin-flow-config-service:gobblin-flow-config-service-client:compileTestJava'.
> Compilation failed; see the compiler error output for details.

**Comment by htran1** [comment]
@abti, that Travis build error is due to another PR removing the jetty dependency that a test in gobblin-restli depended on. That's unrelated to this PR, but I have updated that test to use HTTP status codes from the restli package instead of jetty. Please review.

**Comment by abti** [comment]
Thanks for fixing that too. It seems, it got in while merging old PRs.

**Pull request closed without merging**
