### PR TITLE
Make build compatible with Gradle 2

### PR DESCRIPTION
**Pull request by chavdar**
- Add "ext." references where necessary
- Upgrade pegasus dependency to be compatible with Gradle 2
- Fix gobblin.rest.JobExecutionInfoClient.batchGet(Collection<JobExecutionQuery>) because of change in Pegasus API
- Enable FindBugs for Gradle 2.5+

### CODE REVIEW

**Comment by chavdar** [comment]
@liyinan926  @pcadabam Could you review?

**Comment by kadaan** [comment]
Any chance that this can get done?  What is outstanding?

**Comment by chavdar** [comment]
Yeah, we'll restart working on that. Last thing I remember there were some strange errors with the version of Java 8 that was being used on Travis. We have to see if those are still there.

**Comment by abti** [comment]
@chavdar Is this still relevant?

**Comment by abti** [comment]
https://issues.apache.org/jira/browse/GOBBLIN-157

Please update your PR title with following prefix: [GOBBLIN-157]

**Comment by chavdar** [comment]
This has been fixed in a separate PR.

**Pull request closed without merging**
