### PR TITLE
[GOBBLIN-11] Fix for #1822 and #1823

### PR DESCRIPTION
**Pull request by kadaan**
Add `CLUSTER` to the launcher_type enum in the JobHistory DB
Modified DatabaseJobHistoryStoreV101 to return values of LauncherTypeEnum.CLUSTER as "YARN" and created DatabaseJobHistoryStoreV102 which keeps them as "CLUSTER".

### CODE REVIEW

**Comment by kadaan** [comment]
Fix for #1822 and #1823

**Comment by abti** [comment]
@kadaan will prioritize

**Comment by abti** [comment]
Issue: https://issues.apache.org/jira/browse/GOBBLIN-11

Please update your PR title with following prefix: [GOBBLIN-11]

@kadaan Also, seems like some gobblin-runtime test failed: https://travis-ci.org/apache/incubator-gobblin/jobs/245973138

**Comment by kadaan** [comment]
That is weird. I didn't change anything related to that.  Wonder if it is having a hard time writing to the DB and then that fails the test?

**Comment by abti** [comment]
Possibly, I have seen intermittent failures related to it, though rare

**Pull request merged**
