### PR TITLE
[GOBBLIN-578] Comparison to None should be 'expr is None'

### PR DESCRIPTION
**Pull request by SivaMaplelabs**
Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
https://issues.apache.org/jira/browse/GOBBLIN-578

### Description
- 'expr is None'

### CODE REVIEW

**Comment by SivaMaplelabs** [comment]
@htran1 please review

**Comment by htran1** [comment]
Please create and link a GOBBLIN jira ticket in the title.

**Comment by SivaMaplelabs** [comment]
@htran1 Sure. Thanks

**Comment by SivaMaplelabs** [comment]
@htran1 Have added GOBBLIN JIRA ticket in the title. Thanks

**Pull request closed without merging**
