### PR TITLE
[GOBBLIN-868] Check flow status instead of job status to determine if flow is running

### PR DESCRIPTION
**Pull request by jack-moseley**
Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
    - https://issues.apache.org/jira/browse/GOBBLIN-868

### Description
- [ ] Here are some details about my PR, including screenshots (if applicable):

After updating to use flow level events for job status, this code should be using the flow level status instead of using jobs.

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by jack-moseley** [comment]
@arjun4084346 please review

**Comment by arjun4084346** [comment]
+1

**Comment by jack-moseley** [comment]
@sv2000 please merge

**Comment by sv2000** [comment]
@jack-moseley travis failed. can you check?

**Pull request closed without merging**
